package cli

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseCSVQueries_Basic(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	// Create test CSV
	csvContent := `query,relevant_docs
"How do I reset my password?",docs/auth/password.md
"What are the rate limits?",docs/api/limits.md`

	os.WriteFile(csvPath, []byte(csvContent), 0644)

	queries, err := parseCSVQueries(csvPath)
	if err != nil {
		t.Fatalf("parseCSVQueries failed: %v", err)
	}

	if len(queries) != 2 {
		t.Fatalf("expected 2 queries, got %d", len(queries))
	}

	// Check first query
	if queries[0].Text != "How do I reset my password?" {
		t.Errorf("query 0 text: got %q", queries[0].Text)
	}
	if len(queries[0].RelevantDocs) != 1 || queries[0].RelevantDocs[0] != "docs/auth/password.md" {
		t.Errorf("query 0 relevant docs: got %v", queries[0].RelevantDocs)
	}

	// Check second query
	if queries[1].Text != "What are the rate limits?" {
		t.Errorf("query 1 text: got %q", queries[1].Text)
	}
}

func TestParseCSVQueries_MultipleRelevantDocs(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	csvContent := `query,relevant_docs
"Complex query",doc1.md;doc2.md;doc3.md`

	os.WriteFile(csvPath, []byte(csvContent), 0644)

	queries, err := parseCSVQueries(csvPath)
	if err != nil {
		t.Fatalf("parseCSVQueries failed: %v", err)
	}

	if len(queries) != 1 {
		t.Fatalf("expected 1 query, got %d", len(queries))
	}

	if len(queries[0].RelevantDocs) != 3 {
		t.Errorf("expected 3 relevant docs, got %d", len(queries[0].RelevantDocs))
	}

	expected := []string{"doc1.md", "doc2.md", "doc3.md"}
	for i, doc := range queries[0].RelevantDocs {
		if doc != expected[i] {
			t.Errorf("relevant doc %d: expected %q, got %q", i, expected[i], doc)
		}
	}
}

func TestParseCSVQueries_AlternateHeaders(t *testing.T) {
	tests := []struct {
		name    string
		header  string
		data    string
		wantErr bool
	}{
		{"query,relevant_docs", "query,relevant_docs", "\"Test query\",doc.md", false},
		{"text,relevant", "text,relevant", "\"Test query\",doc.md", false},
		{"question,docs", "question,docs", "\"Test query\",doc.md", false},
		{"id,query,relevant_docs", "id,query,relevant_docs", "q1,\"Test query\",doc.md", false},
		{"missing query col", "foo,relevant_docs", "bar,doc.md", true},
		{"missing relevant col", "query,bar", "\"Test query\",baz", true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			csvPath := filepath.Join(tmpDir, "queries.csv")

			content := tt.header + "\n" + tt.data
			os.WriteFile(csvPath, []byte(content), 0644)

			_, err := parseCSVQueries(csvPath)
			if tt.wantErr && err == nil {
				t.Error("expected error, got nil")
			}
			if !tt.wantErr && err != nil {
				t.Errorf("unexpected error: %v", err)
			}
		})
	}
}

func TestParseCSVQueries_WithIDColumn(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	csvContent := `id,query,relevant_docs
custom-1,"Test query",doc.md`

	os.WriteFile(csvPath, []byte(csvContent), 0644)

	queries, err := parseCSVQueries(csvPath)
	if err != nil {
		t.Fatalf("parseCSVQueries failed: %v", err)
	}

	if queries[0].ID != "custom-1" {
		t.Errorf("expected ID 'custom-1', got %q", queries[0].ID)
	}
}

func TestParseCSVQueries_AutoGeneratedIDs(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	csvContent := `query,relevant_docs
"Query 1",doc1.md
"Query 2",doc2.md`

	os.WriteFile(csvPath, []byte(csvContent), 0644)

	queries, err := parseCSVQueries(csvPath)
	if err != nil {
		t.Fatalf("parseCSVQueries failed: %v", err)
	}

	if queries[0].ID != "imported-1" {
		t.Errorf("expected ID 'imported-1', got %q", queries[0].ID)
	}
	if queries[1].ID != "imported-2" {
		t.Errorf("expected ID 'imported-2', got %q", queries[1].ID)
	}
}

func TestParseCSVQueries_SkipsEmptyRows(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	csvContent := `query,relevant_docs
"Valid query",doc.md
"",empty.md
"   ",whitespace.md
"Another valid",other.md`

	os.WriteFile(csvPath, []byte(csvContent), 0644)

	queries, err := parseCSVQueries(csvPath)
	if err != nil {
		t.Fatalf("parseCSVQueries failed: %v", err)
	}

	if len(queries) != 2 {
		t.Errorf("expected 2 queries (skipping empty), got %d", len(queries))
	}
}

func TestParseCSVQueries_HeaderOnly(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	// Only header, no data - should error (need at least one data row)
	os.WriteFile(csvPath, []byte("query,relevant_docs\n"), 0644)

	_, err := parseCSVQueries(csvPath)
	if err == nil {
		t.Error("expected error for header-only CSV")
	}
}

func TestParseCSVQueries_WithDataRows(t *testing.T) {
	tmpDir := t.TempDir()
	csvPath := filepath.Join(tmpDir, "queries.csv")

	// Header + one empty data row that gets skipped
	os.WriteFile(csvPath, []byte("query,relevant_docs\n\"\",\n"), 0644)

	queries, err := parseCSVQueries(csvPath)
	if err != nil {
		t.Fatalf("parseCSVQueries failed: %v", err)
	}

	// Empty rows are skipped
	if len(queries) != 0 {
		t.Errorf("expected 0 queries (empty rows skipped), got %d", len(queries))
	}
}

func TestParseCSVQueries_FileNotFound(t *testing.T) {
	_, err := parseCSVQueries("/nonexistent/path/queries.csv")
	if err == nil {
		t.Error("expected error for nonexistent file")
	}
}

func TestParseJSONQueries_Basic(t *testing.T) {
	tmpDir := t.TempDir()
	jsonPath := filepath.Join(tmpDir, "queries.json")

	jsonContent := `{
  "queries": [
    {"id": "q1", "text": "How do I reset my password?", "relevant_docs": ["password.md"]},
    {"id": "q2", "text": "What are rate limits?", "relevant_docs": ["limits.md", "quotas.md"]}
  ]
}`

	os.WriteFile(jsonPath, []byte(jsonContent), 0644)

	queries, err := parseJSONQueries(jsonPath)
	if err != nil {
		t.Fatalf("parseJSONQueries failed: %v", err)
	}

	if len(queries) != 2 {
		t.Fatalf("expected 2 queries, got %d", len(queries))
	}

	if queries[0].ID != "q1" {
		t.Errorf("query 0 ID: got %q", queries[0].ID)
	}
	if queries[0].Text != "How do I reset my password?" {
		t.Errorf("query 0 text: got %q", queries[0].Text)
	}
	if len(queries[1].RelevantDocs) != 2 {
		t.Errorf("query 1 relevant docs count: got %d", len(queries[1].RelevantDocs))
	}
}

func TestParseJSONQueries_AutoGeneratesIDs(t *testing.T) {
	tmpDir := t.TempDir()
	jsonPath := filepath.Join(tmpDir, "queries.json")

	jsonContent := `{
  "queries": [
    {"text": "Query without ID", "relevant_docs": ["doc.md"]}
  ]
}`

	os.WriteFile(jsonPath, []byte(jsonContent), 0644)

	queries, err := parseJSONQueries(jsonPath)
	if err != nil {
		t.Fatalf("parseJSONQueries failed: %v", err)
	}

	if queries[0].ID != "imported-1" {
		t.Errorf("expected auto-generated ID 'imported-1', got %q", queries[0].ID)
	}
}

func TestParseJSONQueries_InvalidJSON(t *testing.T) {
	tmpDir := t.TempDir()
	jsonPath := filepath.Join(tmpDir, "queries.json")

	os.WriteFile(jsonPath, []byte("not valid json"), 0644)

	_, err := parseJSONQueries(jsonPath)
	if err == nil {
		t.Error("expected error for invalid JSON")
	}
}

func TestParseJSONQueries_EmptyQueries(t *testing.T) {
	tmpDir := t.TempDir()
	jsonPath := filepath.Join(tmpDir, "queries.json")

	jsonContent := `{"queries": []}`
	os.WriteFile(jsonPath, []byte(jsonContent), 0644)

	queries, err := parseJSONQueries(jsonPath)
	if err != nil {
		t.Fatalf("parseJSONQueries failed: %v", err)
	}

	if len(queries) != 0 {
		t.Errorf("expected 0 queries, got %d", len(queries))
	}
}

func TestParseJSONQueries_FileNotFound(t *testing.T) {
	_, err := parseJSONQueries("/nonexistent/path/queries.json")
	if err == nil {
		t.Error("expected error for nonexistent file")
	}
}
